env:
  browser: true
  es2021: true
  node: true
parserOptions:
  sourceType: "module"
  ecmaFeatures:
    jsx: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:react/jsx-runtime"
